[meta]
use_amp = false
cudnn_enable = true
seed = 2024
use_ema = false

[acoustic]
path = "acoustics.feature.transforms"

[dataloader]
path = "dataset.noisy_dataset_1cnl.MyDataloader"

[loss_function]
name = "KL_loss"

[optimizer]
type = "AdamW"

[scheduler]
type = "ExponentialLR"

[trainer]
path = "trainer_inferencer.trainer.Trainer"

[EM_algo]
path = "method.vem_rir_omit3bin.VEM"

[model]
path = "model.osn.OSN_bimamba11.BiSpatialNet"

[acoustic.args]
sr = 16000
n_fft = 512
win_len = 512
hop_len = 128
win_type = "hann"
n_mel = 80

[dataloader.args]
src_pathlist = [
    "config/src_train.txt",
    "config/src_valid.txt",
    "config/src_test.txt",
]
rir_pathlist = [
    "config/rir_train.txt",
    "config/rir_valid.txt",
    "config/rir_test.txt",
]
noise_pathlist = [
    "config/noise_train.txt",
    "config/noise_valid.txt",
    "config/noise_test.txt",
]
snr_range = [5, 20]
seq_lenlist = [3.0, 6.0, 3.0]
batchsize = [4, 4, 1]
num_workers = 8
seeds = [2022, 2023, 2024]
pin_memory = true
prefetch_factor = 1
persistent_workers = true
rank = 0
sr = 16000
noisy_proportion = 1

[loss_function.args]
zero_step = 0
warmup_step = 100
hold_step = 100
beta = 1
eps = 0.0001
bidir = false

[optimizer.args]
lr = 0.001
betas = [0.9, 0.99]

[scheduler.args]
gamma = 0.9

[trainer.train]
epochs = 50
clip_grad_norm_value = 10
save_ckpt_interval = 1
grad_accumulation_steps = 1

[trainer.validation]
interval = 1
save_max_metric = false

[EM_algo.args]
CTF_len = 30
errvar_init = 1
max_steps = 100
min_steps = 0
eda_factor_mu = 0.7
eda_factor_var = 0.7
eda_factor_CTF = 0.0
eda_factor_ErrVar = 0.0

[model.args]
dim_input = 1
dim_output = 1
dim_squeeze = 8
num_layers = 8
num_freqs = 257
encoder_kernel_size = 3
dim_hidden = 96
dropout = [0, 0, 0]
kernel_size = [5, 3]
conv_groups = [8, 8]
norms = ["LN", "LN", "LN", "LN", "LN", "LN"]
full_share = 0
attention = "mamba(16,4)"
